// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHi4wZ2i8iQBfofKRWgjik0ZbNMrWLQsY',
    appId: '1:257911196069:android:3e2e5ef6c5ff9ace44804c',
    messagingSenderId: '257911196069',
    projectId: 'gen-usd',
    storageBucket: 'gen-usd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7TcqqeGqWbmGbOqWae6vTCYJ4jg4GsvU',
    appId: '1:257911196069:ios:6e98f5ecd2521cfb44804c',
    messagingSenderId: '257911196069',
    projectId: 'gen-usd',
    storageBucket: 'gen-usd.firebasestorage.app',
    iosBundleId: 'com.example.earnWatchingAds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7TcqqeGqWbmGbOqWae6vTCYJ4jg4GsvU',
    appId: '1:257911196069:ios:6e98f5ecd2521cfb44804c',
    messagingSenderId: '257911196069',
    projectId: 'gen-usd',
    storageBucket: 'gen-usd.firebasestorage.app',
    iosBundleId: 'com.example.earnWatchingAds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXTUz3tIxmA0MXcbaHXXC5c6o8ciazy_U',
    appId: '1:257911196069:web:5cfc9a6ac3f17c3844804c',
    messagingSenderId: '257911196069',
    projectId: 'gen-usd',
    authDomain: 'gen-usd.firebaseapp.com',
    storageBucket: 'gen-usd.firebasestorage.app',
  );
}
